VOXEL: removed unused opencl functions
stringInput.cl:72:21: error: use of undeclared identifier 'VoxelType'
stringInput.cl:75:14: error: must use 'enum' tag to refer to type 'VoxelType'