Revert "LIBS: updated google benchmark"
This reverts commit a7f00f47adfc5da6268fc3f57fb089f7869b5339.

msvc compile errors

perf_counters.cc(118,39): error C2491: 'benchmark::internal::PerfCounters::kSupported': definition of dllimport static data member not allowed