CMAKE: attempt to fix mingw build by linking msvcrt
undefined reference to __imp__set_abort_behavior

most likely introduced by 608d9447d8401fcb73be1b157894a226b56f0a04