GLM: compile error, ortho and lookAt are defined at matrix_transform
This may be an issue of using latest glm version 0.9.9 locally

error: ortho is not a member of glm
error: lookAt is not a member of glm